namespace Subspace.Rtsp
{
    public enum RtspStatusCode
    {
        Continue = 100,
        OK = 200,
        Created = 201,
        LowOnStorageSpace = 250,
        MultipleChoices = 300,
        MovedPermanently = 301,
        MovedTemporarily = 302,
        SeeOther = 303,
        UseProxy = 305,
        BadRequest = 400,
        Unauthorized = 401,
        PaymentRequired = 402,
        Forbidden = 403,
        NotFound = 404,
        MethodNotAllowed = 405,
        NotAcceptable = 406,
        ProxyAuthenticationRequired = 407,
        RequestTimeout = 408,
        Gone = 410,
        LengthRequired = 411,
        PreconditionFailed = 412,
        RequestEntityTooLarge = 413,
        RequestUriTooLong = 414,
        UnsupportedMediaType = 415,
        InvalidParameter = 451,
        IllegalConferenceIdentifier = 452,
        NotEnoughBandwidth = 453,
        SessionNotFound = 454,
        MethodNotValidInThisState = 455,
        HeaderFieldNotValid = 456,
        InvalidRange = 457,
        ParameterIsReadOnly = 458,
        AggregateOperationNotAllowed = 459,
        OnlyAggregateOperationAllowed = 460,
        UnsupportedTransport = 461,
        DestinationUnreachable = 462,
        InternalServerError = 500,
        NotImplemented = 501,
        BadGateway = 502,
        ServiceUnavailable = 503,
        GatewayTimeout = 504,
        RtspVersionNotSupported = 505,
        OptionNotSupported = 551
    }
}
